"""Detection signals.

Signal 1 (Groq LLM) and Signal 2 (pure-Python stylometry). The combination of
the two into a single ai_score lives in scoring.combine().
"""

import json
import os
import re
import statistics

from groq import Groq

MODEL = "llama-3.3-70b-versatile"

_SYSTEM_PROMPT = (
    "You are an AI-content detector for a writing platform. Judge whether the "
    "given text was written by a human or generated by an AI, based on semantic "
    "and stylistic coherence. Respond ONLY with strict JSON of the form "
    '{"p_ai": <number between 0 and 1>, "rationale": "<one short sentence>"}. '
    "p_ai is your estimated probability the text is AI-generated: 0 = clearly "
    "human, 1 = clearly AI, 0.5 = genuinely unsure. Do not include any text "
    "outside the JSON."
)

_client = None


def _get_client() -> Groq:
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY is not set (check your .env)")
        _client = Groq(api_key=api_key)
    return _client


def llm_signal(text: str) -> dict:
    """Signal 1: ask Groq for an AI-likelihood assessment.

    Returns {"p_ai": float in [0,1], "rationale": str}. p_ai is clamped to the
    valid range; on a malformed response we fall back to maximal uncertainty
    (0.5) rather than guessing, which keeps a broken signal from producing a
    confident (possibly false-positive) verdict.
    """
    client = _get_client()
    resp = client.chat.completions.create(
        model=MODEL,
        temperature=0,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
    )
    raw = resp.choices[0].message.content
    try:
        data = json.loads(raw)
        p_ai = float(data["p_ai"])
        rationale = str(data.get("rationale", "")).strip()
    except (json.JSONDecodeError, KeyError, TypeError, ValueError):
        return {"p_ai": 0.5, "rationale": "signal error: could not parse model response"}

    p_ai = max(0.0, min(1.0, p_ai))
    return {"p_ai": p_ai, "rationale": rationale}


# --- Signal 2: stylometric heuristics (pure Python) -------------------------
#
# Three sub-metrics, each mapped to a partial AI-likelihood in [0,1] by linear
# interpolation between a human-leaning and an AI-leaning threshold, then
# averaged. AI/formal prose tends to be uniform with long, sophisticated words;
# casual human writing is more varied with shorter words.
#
# NOTE (calibration): the original spec named type-token ratio and punctuation
# density, but calibration against the sample texts showed both cluster tightly
# across AI and human at typical submission length (~40-60 words) and don't
# discriminate. They were replaced with average word length and long-word
# fraction, which separate cleanly. See planning.md section 1.
#
# Each entry: (human_value, ai_value). _interp is direction-agnostic, so it
# returns "how AI-like is this metric" whether high or low means AI.
_HUMAN_LEANING = {"cv": 0.60, "avg_word_len": 4.5, "long_word_ratio": 0.15}
_AI_LEANING = {"cv": 0.25, "avg_word_len": 6.0, "long_word_ratio": 0.45}

# Below this word count the statistics are too unstable to trust; we widen
# uncertainty by pulling the stylometry p_ai toward 0.5.
_MIN_RELIABLE_WORDS = 40
_LONG_WORD_CHARS = 7

_SENTENCE_SPLIT = re.compile(r"[.!?]+(?:\s+|$)")
_WORD = re.compile(r"[A-Za-z']+")


def _interp(value: float, human: float, ai: float) -> float:
    """Map a metric to [0,1] AI-likelihood, clamped, direction-agnostic."""
    if human == ai:
        return 0.5
    frac = (value - human) / (ai - human)
    return max(0.0, min(1.0, frac))


def stylometry_signal(text: str) -> dict:
    """Signal 2: structural properties of the writing.

    Returns {"p_ai": float, "metrics": {cv, avg_word_len, long_word_ratio,
    word_count}}. Short texts are pulled toward 0.5 (statistics unreliable).
    """
    words = _WORD.findall(text.lower())
    word_count = len(words)
    sentences = [s for s in _SENTENCE_SPLIT.split(text) if s.strip()]

    # Sentence-length coefficient of variation (stdev / mean of words/sentence).
    sent_word_counts = [len(_WORD.findall(s)) for s in sentences] or [word_count]
    mean_len = statistics.mean(sent_word_counts) if sent_word_counts else 0
    if len(sent_word_counts) >= 2 and mean_len > 0:
        cv = statistics.pstdev(sent_word_counts) / mean_len
    else:
        cv = 0.5  # not enough sentences to judge rhythm

    # Lexical sophistication: average word length and share of long words.
    avg_word_len = statistics.mean(len(w) for w in words) if words else 0.0
    long_word_ratio = (
        sum(1 for w in words if len(w) >= _LONG_WORD_CHARS) / word_count
        if word_count else 0.0
    )

    sub_scores = [
        _interp(cv, _HUMAN_LEANING["cv"], _AI_LEANING["cv"]),
        _interp(avg_word_len, _HUMAN_LEANING["avg_word_len"], _AI_LEANING["avg_word_len"]),
        _interp(long_word_ratio, _HUMAN_LEANING["long_word_ratio"], _AI_LEANING["long_word_ratio"]),
    ]
    p_ai = sum(sub_scores) / len(sub_scores)

    # Down-weight unreliable short texts by blending toward 0.5.
    if word_count < _MIN_RELIABLE_WORDS:
        reliability = word_count / _MIN_RELIABLE_WORDS
        p_ai = p_ai * reliability + 0.5 * (1 - reliability)

    return {
        "p_ai": round(max(0.0, min(1.0, p_ai)), 4),
        "metrics": {
            "cv": round(cv, 4),
            "avg_word_len": round(avg_word_len, 4),
            "long_word_ratio": round(long_word_ratio, 4),
            "word_count": word_count,
        },
    }
